### ISSUE TITLE
Org-mode: SHIFT-TAB not working in Windows-SSH-shell or Debian-tty (sometimes "M-[ ~ is undefined")

### ISSUE THREAD

**Issue by buhtz** [daviwil/runemacs#67]
# Introduction
I am still building my `init.el` based on your great _emacs from scratch_ videos. Now in `org-mode` I experience some wired behavior of the SHIFT-TAB key when (un)folding headings in an `.org` file.

# Problem
In some cases SHIFT-TAB creates a `M-[ ~ is undefined` message or simply does not work without an error message.

# System
Debian 11
```
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
 of 2021-03-28, modified by Debian
Copyright (C) 2020 Free Software Foundation, Inc.

```
# Minimal init.el
This can be used for reproduction.
```
;; === Package setup ===
(require 'package)
(setq package-archives '(("melpa" . "https://melpa.org/packages/")
			 ("org" . "https://orgmode.org/elpa/")
			 ("elpa" . "https://elpa.gnu.org/packages/")))
(package-initialize)

;; === use-package ==
;; use-package to simplify the config file
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure 't)

(use-package org)

```

# Description of the behavior in multiple cases

## Windows SSH-terminal

Form a Windows 10 client and its usual command prompt (not PowerShell, not Terminal.app) I log into my machine via SSH and (of course) use emacs in none-gui mode then. TAB works. But SHIFT-TAB produce the `M-[ ~ is undefined` error.

## A tty terminal (Debian 11)
Here TAB works. But S-TAB does not. The latter does **not** produce any error message. There is simply no reaction on that button.

## Cases in where it is NOT reproducable

- Gui mode in XFCE session on Debian 11
- Terminal emulator (terminator) in a XFCE session on Debian 11
- SSH terminal from Debian 11

## Sidenotes
There is a stackoverflow QA for this: https://stackoverflow.com/q/3518846
The solution there does not work for me (Emacs from Debian 11).

This problem is totally out of my scope of understanding. But I am sure you are the one who are able to describe this in a way that even a novice can understand it.

**Comment by buhtz** [comment]
I think this problem is to special and I will close it from here.
But maybe you can update your documentation about that video with it.

One aspect may causing this problem is how the different terminals interpret characters and pressed keys. It is not clear for me yet.

But one other very important aspect relating to your `init.el` is the option `(setq evil-want-C-i-jump nil)` you use in your `evil-mode` section. In the video you didn't describe it in detailed. I missed that option first because I do not set something up that I do not understand - even if David says "Do it.". 😄 But that was it. Using this option make the TAB problem disappear.

Maybe you simple modify your `init.el` like this?

`(setq evil-want-C-i-jump nil)  ; important to make the TAB key work in org-mode
`
Best wishes to you David
Christian

**Comment by iFHiGM** [comment]
Hi, @Codeberg-AsGithubAlternative-buhtz , thank you for your thoughts on this question.

I ran into the same problem just now.

My environment is:
- I am using emacs (version: 27.1) on wsl1 (install kali-linux) on windows11 (dev, build 22494)
- At the same time, I choose windows terminal preview as my terminal emulator.

Like you, when I typed `S-tab`, emacs complained about "M-[ ~ is undefined", I browsed the solutions in [StackOverflow given in the issue](https://stackoverflow.com/q/3518846), which gave me inspiration.

I thought, before I opened emacs, I replaced the bash environment variable `TERM`.
It turned out to be equal to `xterm-256color`.
In order to make the terminal support true-color (24bit color), I changed it to `st-direct` (just test).
When I open org again and use `S-Tab`, it doesn't work anymore.

Then I reset my `TERM` settings, and then the `S-Tab` is restored. I don't know if your situation is the same as mine, but I hope to provide a reference and help to people who also encounter this problem.

> One aspect may causing this problem is how the different terminals interpret characters and pressed keys. It is not clear for me yet.

I think your conclusion should be correct for my situation.
